/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products_/index'
import { Route as AuthSignupImport } from './routes/_auth/signup'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as appProfileImport } from './routes/(app)/profile'
import { Route as appCheckoutImport } from './routes/(app)/checkout'
import { Route as appCartImport } from './routes/(app)/cart'
import { Route as ProductsProductIdIndexImport } from './routes/products_/$productId/index'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProductsIndexRoute = ProductsIndexImport.update({
  id: '/products_/',
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)

const appProfileRoute = appProfileImport.update({
  id: '/(app)/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const appCheckoutRoute = appCheckoutImport.update({
  id: '/(app)/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const appCartRoute = appCartImport.update({
  id: '/(app)/cart',
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const ProductsProductIdIndexRoute = ProductsProductIdIndexImport.update({
  id: '/products_/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/(app)/cart': {
      id: '/(app)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof appCartImport
      parentRoute: typeof rootRoute
    }
    '/(app)/checkout': {
      id: '/(app)/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof appCheckoutImport
      parentRoute: typeof rootRoute
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileImport
      parentRoute: typeof rootRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/products_/': {
      id: '/products_/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/products_/$productId/': {
      id: '/products_/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/checkout': typeof appCheckoutRoute
  '/profile': typeof appProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/products': typeof ProductsIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/cart': typeof appCartRoute
  '/checkout': typeof appCheckoutRoute
  '/profile': typeof appProfileRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/products': typeof ProductsIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/(app)/cart': typeof appCartRoute
  '/(app)/checkout': typeof appCheckoutRoute
  '/(app)/profile': typeof appProfileRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/products_/': typeof ProductsIndexRoute
  '/products_/$productId/': typeof ProductsProductIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/products'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/cart'
    | '/checkout'
    | '/profile'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/products'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/(app)/cart'
    | '/(app)/checkout'
    | '/(app)/profile'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/signup'
    | '/products_/'
    | '/products_/$productId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  appCartRoute: typeof appCartRoute
  appCheckoutRoute: typeof appCheckoutRoute
  appProfileRoute: typeof appProfileRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  appCartRoute: appCartRoute,
  appCheckoutRoute: appCheckoutRoute,
  appProfileRoute: appProfileRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/(app)/cart",
        "/(app)/checkout",
        "/(app)/profile",
        "/products_/",
        "/products_/$productId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/signup"
      ]
    },
    "/(app)/cart": {
      "filePath": "(app)/cart.tsx"
    },
    "/(app)/checkout": {
      "filePath": "(app)/checkout.tsx"
    },
    "/(app)/profile": {
      "filePath": "(app)/profile.tsx"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx",
      "parent": "/_auth"
    },
    "/products_/": {
      "filePath": "products_/index.tsx"
    },
    "/products_/$productId/": {
      "filePath": "products_/$productId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
